name: Build desktop installers

on:
  workflow_dispatch:
  push:
    branches:
      - chore/deployment-alignment-suse-rpm

jobs:
  build-linux-rpm:
    name: Linux RPM
    runs-on: ubuntu-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      ELECTRON_BUILDER_DISABLE_UPDATER: 'true'
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install rpm tool
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot

      - name: Install dependencies
        run: npm ci

      - name: Build web assets (Vite)
        run: npm run build

      - name: Build RPM (x86_64)
        run: npx electron-builder --linux rpm --x64

      - name: Build RPM (aarch64)
        run: npx electron-builder --linux rpm --arm64

      - name: Upload RPM x86_64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-x86_64
          path: release/*x86_64.rpm

      - name: Upload RPM aarch64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-aarch64
          path: release/*.aarch64.rpm

  build-windows-exe:
    name: Windows EXE
    runs-on: windows-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      ELECTRON_BUILDER_DISABLE_UPDATER: 'true'
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets (Vite)
        run: npm run build

      - name: Build EXE (NSIS)
        run: npx electron-builder --win nsis

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: release/*.exe

  build-macos-dmg:
    name: macOS DMG
    runs-on: macos-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      ELECTRON_BUILDER_DISABLE_UPDATER: 'true'
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets (Vite)
        run: npm run build

      - name: Build DMG
        run: npx electron-builder --mac dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: release/*.dmg

  